services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    command: php artisan serve --host=0.0.0.0 --port=8000
    environment:
      - APP_ENV=local
    env_file:
      - .env

networks:
  default:
    driver: bridge
